import lib.stream as stream
from lib.sink import Sink
import mpd
import logging


class AudioOutput:
    def __init__(self, type: str, sink_obj: Sink):
        self.type = type
        self.sink_obj = sink_obj
    
    def get_type(self) -> str:
        """Get the type of audio output."""
        return self.type

    def to_config_dict(self) -> dict[str, str]:
        """Convert AudioOutput to config dict format."""
        type=self.get_type()
        name=f"pw_{self.sink_obj.get_name()}"
        sink=f"sink.{self.sink_obj.get_name()}"
        return {
            'type': type,
            'sink': sink,
            'name': name
        }
    
    def to_mpd_config(self) -> str:
        """Convert AudioOutput to MPD config format."""
        # Prepare MPD audio_output config block
        type=self.get_type()
        name=f"pw_{self.sink_obj.get_name()}"
        sink=f"sink.{self.sink_obj.get_name()}"
        # Use Pulseaudio sink 
        type="pulse"
        return f"audio_output {{\n    type \"{type}\"\n    name \"{name}\"\n    sink \"{sink}\"\n}}"
    


class MPDInstance:
    def __init__(self, name: str, bind_addr: str, port: int, stream_obj: stream.Stream) -> None:
        self.name = name
        self.bind_addr = bind_addr
        self.port = port
        self.stream = stream_obj

    def to_mpd_config(self) -> str:
        """Convert MPDInstance to MPD config format."""
        # Prepare MPD config block
        config = f"# MPD config for {self.name}\n"
        config += "# This file is auto-generated by MPDRussoundPi. Do not edit manually.\n"
        config += f"port \"{self.port}\"\n"
        config += f"bind_to_address \"{self.bind_addr}\"\n"
        if hasattr(self, 'audio_output'):
            config += self.audio_output.to_mpd_config()
        return config

    def add_audio_output(self, audio_output: AudioOutput):
        """Add an audio output to the MPD instance."""
        self.audio_output = audio_output



    def play(self) -> None:
        """Connect to MPD instance and play the stream."""
        try:
            client = mpd.MPDClient()
            client.connect('localhost', self.port)  # pyright: ignore[reportUnknownMemberType]
            playlist_url = self.stream.get_url()
            if playlist_url:
                client.add(playlist_url) # pyright: ignore[reportUnknownMemberType]
                client.play() # pyright: ignore[reportUnknownMemberType]
                logging.info(f"Now playing stream: {self.stream.get_name()}")
                #print(f"Now playing stream: {self.stream.get_name()}")
            client.close() # pyright: ignore[reportUnknownMemberType]
        except (mpd.ConnectionError, OSError) as e:
            logging.error(f"Could not connect to MPD for stream '{self.stream.get_name()}' on port {self.port}: {e}")

    def stop(self) -> None:
        """Stop playback of the stream in MPD."""
        try:
            client = mpd.MPDClient()
            client.connect('localhost', self.port) # pyright: ignore[reportUnknownMemberType]
            client.stop() # pyright: ignore[reportUnknownMemberType]
            client.close() # pyright: ignore[reportUnknownMemberType]
            logging.info(f"Stopped stream: {self.stream.get_name()}")
            #print(f"Stopped stream: {self.stream.get_name()}")
        except (mpd.ConnectionError, OSError) as e:
            logging.error(f"Could not connect to MPD for stream '{self.stream.get_name()}' on port {self.port}: {e}")

    def get_stream_status(self) -> str | None:
        """Get the current status of the stream from MPD."""
        try:
            client = mpd.MPDClient()
            client.connect('localhost', self.port) # pyright: ignore[reportUnknownMemberType]
            status = str(client.status().get('state')) # pyright: ignore[reportUnknownVariableType, reportUnknownMemberType]
            current_song = str(client.currentsong().get('title', 'N/A')) # pyright: ignore[reportUnknownVariableType, reportUnknownMemberType]
            client.close() # pyright: ignore[reportUnknownMemberType]
            logging.info(f"Stream '{self.stream.get_name()}' status: {status}, current song: {current_song}")
            #print(f"Stream: {self.stream.get_name()}, Status: {status}, Current Song: {current_song} \n")
            return status
        except (mpd.ConnectionError, OSError) as e:
            logging.error(f"Could not connect to MPD for stream '{self.stream.get_name()}' on port {self.port}: {e}")




def config2mpd(config: dict, available_sinks: dict[str, Sink], ignore_missing_sinks: bool=False) -> MPDInstance | None:
    """Convert config dict to MPDInstance object."""

    name = config.get('name')
    bind_addr = config.get('bind_to_addr', '0.0.0.0')
    port = config.get('port')

    # process stream
    stream_url = config.get('stream')
    stream_obj = stream.Stream(stream_url, name)

    instance = MPDInstance(name, bind_addr, port, stream_obj)

    # process audio output and sink information if provided
    audio_output = config.get('audio_output', {})
    sink_name = str(audio_output.get('sink'))
    sink_type = str(audio_output.get('type'))

    if sink_name: 
        if sink_name not in available_sinks:
            if not ignore_missing_sinks:
                logging.error(f"Sink '{sink_name}' specified for stream '{name}' not found in config sinks.")
                return None
            logging.warning(f"Continuing without existing sink '{sink_name}' for stream '{name}'.")
        else:
            logging.info(f"Sink '{sink_name}' found for stream '{name}'.")
            audio_output_obj = AudioOutput(sink_type, available_sinks[sink_name])
            instance.add_audio_output(audio_output_obj)

    return instance