---
- hosts: musicpi
  tasks:
    # Run apt-get update and apt-get upgrade 
    - include_tasks: ../tasks/update.yml
      tags: 
        - update
        - init

    # Install dependancies from apt
    - name: Install dependancies from apt
      become: yes
      apt: name={{item}} state=present
      with_items:
        - git
        - python3
        - python3-pip
        - python3-venv
        - ser2net
        - curl
        - build-essential
      tags:
        - init


    - name: Copy ser2net configuration file
      become: yes
      copy:
        dest: /etc/
        src: ../../mpdrussoundpi/ser2net/ser2net.yaml
      notify: Restart ser2net
      tags:
        - init

    - name: Ensure ser2net is running
      systemd:
        name: ser2net
        state: started
        enabled: yes
      tags:
        - init

    - name: Run a module inside a virtual environment
      block:
        - name: Ensure the virtual environment exists
          pip:
            name: psutil
            virtualenv: "{{ venv_dir }}"
            # On Debian-based systems the correct python*-venv package must be installed to use the `venv` module.
            virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
        - name: Install russound lib and dependencies
          ansible.builtin.pip:
            name: russound
            virtualenv: "{{ venv_dir }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
        venv_dir: ~/russound-venv
        venv_python: "{{ venv_dir }}/bin/python"
      tags:
        - init

    - name: Clone/update MPDRussoundPi Repository
      ansible.builtin.git:
        repo: https://github.com/itcorner/MPDRussoundPi.git
        dest: ~/MPDRussoundPi
        update: true
      tags:
        - new

  handlers:
    - name: Restart ser2net
      systemd:
        name: ser2net
        state: restarted

