---
- hosts: musicpi
  vars:
    mpd_russoundpi_repo: "https://github.com/itcorner/MPDRussoundPi.git"
    mpd_russoundpi_dest: "~/MPDRussoundPi"
    mpd_russoundpi_scripts: "{{ mpd_russoundpi_dest }}/mpdrussoundpi/russound"
    mpd_russoundpi_config: "{{ mpd_russoundpi_scripts }}/config.json"
    venv_dir: "~/russound-venv"
  tasks:
    # Run apt-get update and apt-get upgrade 
    - include_tasks: ../tasks/update.yml
      tags: 
        - update
        - init

    # Install dependencies from apt
    - name: Install dependencies from apt
      become: yes
      apt: name={{item}} state=present
      with_items:
        - git
        - python3
        - python3-pip
        - python3-venv
        - python3-mpd
        - ser2net
        - mpd
        - mpc
        - timidity
      tags:
        - init


    - name: Copy ser2net configuration file
      become: yes
      copy:
        dest: /etc/
        src: ../../mpdrussoundpi/ser2net/ser2net.yaml
      notify: Restart ser2net
      tags:
        - init

    - name: Ensure ser2net is running
      systemd:
        name: ser2net
        state: started
        enabled: yes
      tags:
        - init

    - name: Run a module inside a virtual environment
      block:
        - name: Ensure the virtual environment exists
          pip:
            name: psutil
            virtualenv: "{{ venv_dir }}"
            # On Debian-based systems the correct python*-venv package must be installed to use the `venv` module.
            virtualenv_command: "{{ ansible_python_interpreter }} -m venv --system-site-packages"
        - name: Install russound lib and dependencies
          ansible.builtin.pip:
            name: russound
            virtualenv: "{{ venv_dir }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
        venv_python: "{{ venv_dir }}/bin/python3"
      tags:
        - init

    - name: Clone/update MPDRussoundPi Repository
      ansible.builtin.git:
        repo: "{{ mpd_russoundpi_repo }}"
        dest: "{{ mpd_russoundpi_dest }}"
        update: true
      tags:
        - new

    - name: Run MPD setup scripts
      block:
        - name: Setup audio system
          #setup audio system
          ansible.builtin.command: "{{ venv_dir }}/bin/python3 {{ mpd_russoundpi_scripts }}/audiosetup.py --install {{ mpd_russoundpi_config }}"
        - name: Setup MPD services
          #setup MPD services configuration and auto-start and start services
          ansible.builtin.command: "{{ venv_dir }}/bin/python3 {{ mpd_russoundpi_scripts }}/mpdsetup.py {{ item }} {{ mpd_russoundpi_config }}"
          with_items:
            - "--install"
            - "--enable"
            - "--start"
        - name: Setup MPD control service
          #setup MPD control service and enable it to auto-start and start the service
          ansible.builtin.command: "{{ venv_dir }}/bin/python3 {{ mpd_russoundpi_scripts }}/mpdctrl.py {{ item }} {{ mpd_russoundpi_config }}"
          with_items:
            - "--install"
            - "--enable"
            - "--start"
      tags:
        - new

  handlers:
    - name: Restart ser2net
      systemd:
        name: ser2net
        state: restarted

