import lib.readconfig as readconfig
#from lib.mpdinstance import MPDInstance, config2mpd
from lib.audiodevice import AudioDevice, config2audiodevice
import argparse
import os
import subprocess
import logging
import time

LOCKFILE = '/tmp/audio_setup.lock'

MPD_CONFIG_DIR = os.path.expanduser('~/.config/mpd/')
PULSE_CONFIG = os.path.expanduser('~/.config/pulse/default.pa')

#PIPEWIRE_CONFIG = os.path.expanduser('~/.config/pipewire/pipewire-pulse.conf.d/remapped-sinks.conf')
PIPEWIRE_CONFIG = os.path.expanduser('~/.config/pipewire/pipewire.conf.d/remapped-sinks.conf')

WIREPLUMBER_CONFIG = os.path.expanduser('~/.config/wireplumber/wireplumber.conf.d/card-modes.conf')

logging.basicConfig(filename='russound_debugging.log', level=logging.DEBUG,
                    format='%(asctime)s:%(name)s:%(levelname)s:%(funcName)s():%(message)s')

def acquire_lock():
    """Acquire a lock to prevent multiple instances of the script from running simultaneously."""
    import os
    import sys

    if os.path.exists(LOCKFILE):
        print("Another instance of the script is already running. Exiting.")
        print(f"If you are sure no other instance is running, delete the lock file: {LOCKFILE}")
        sys.exit(1)

    with open(LOCKFILE, 'w') as f:
        f.write(str(os.getpid()))

def release_lock():
    """Release the lock when the script finishes."""
    import os

    if os.path.exists(LOCKFILE):
        # Check if the PID in the lock file matches the current process before removing it
        with open(LOCKFILE, 'r') as f:
            pid = f.read()
            if pid == str(os.getpid()):
                os.remove(LOCKFILE)


def detect_audio_processor() -> dict[str, bool]:
    """Detect active audio processor and return the selected processor."""
    pipewire_active = subprocess.run(['systemctl', '--user', 'is-active', 'pipewire'], 
                                        capture_output=True).returncode == 0
    pulseaudio_active = subprocess.run(['systemctl', '--user', 'is-active', 'pulseaudio'], 
                                        capture_output=True).returncode == 0
    processors : dict[str, bool] = {}
    processors['pipewire'] = pipewire_active
    processors['pulseaudio'] = pulseaudio_active
    logging.debug(f"Detected audio processor status: {processors}")
    return processors

def create_pipewire_config(device_dict: dict[str, AudioDevice]):
    """Create PipeWire configuration file based on the provided device dictionary."""
    print("Creating PipeWire configuration...")
    logging.debug(f"Creating PipeWire config with devices: {list(device_dict.keys())}")
    os.makedirs(os.path.dirname(PIPEWIRE_CONFIG), exist_ok=True)

    with open(PIPEWIRE_CONFIG, 'w') as f:
        f.write("# This file is auto-generated by MPDRussoundPi audiosetup.py\n")
        f.write("# Do not edit this file directly. Instead, edit config.json and run audiosetup.py with --initialize option.\n\n")
        f.write("# PipeWire config for remapped sinks\n\n")
        f.write("context.modules = [\n")
        for device in device_dict.values():
            f.write(device.get_pipewire_sink_config())
        f.write("]\n")

    print(f"Created PipeWire config: {PIPEWIRE_CONFIG}")
    #subprocess.run(['systemctl', '--user', 'restart', 'pipewire'], check=False)

def create_wireplumber_config(device_dict: dict[str, AudioDevice]):
    """Create WirePlumber configuration file based on the provided device dictionary."""
    print("Creating WirePlumber configuration...")
    logging.debug(f"Creating WirePlumber config with devices: {list(device_dict.keys())}")
    os.makedirs(os.path.dirname(WIREPLUMBER_CONFIG), exist_ok=True)

    with open(WIREPLUMBER_CONFIG, 'w') as f:
        f.write("# This file is auto-generated by MPDRussoundPi audiosetup.py\n")
        f.write("# Do not edit this file directly. Instead, edit config.json and run audiosetup.py with --initialize option.\n\n")
        f.write("context.rules = [\n")
        #f.write("monitor.alsa.rules = [\n")
        for device in device_dict.values():
            f.write(device.get_wireplumber_card_config())
        f.write("]\n")

    print(f"Created WirePlumber config: {WIREPLUMBER_CONFIG}")
    # Reload PipeWire/WirePlumber configuration
    subprocess.run(['systemctl', '--user', 'restart', 'wireplumber'], check=False)
    #subprocess.run(['systemctl', '--user', 'restart', 'pipewire'], check=False)

def create_pulse_config(device_dict: dict[str, AudioDevice]):
    """Create PulseAudio configuration file based on the provided device dictionary."""
    print("Creating PulseAudio configuration...")
    logging.debug(f"Creating PulseAudio config with devices: {list(device_dict.keys())}")

    os.makedirs(os.path.dirname(PULSE_CONFIG), exist_ok=True)

    with open(PULSE_CONFIG, 'w') as f:
        f.write("# This file is auto-generated by MPDRussoundPi audiosetup.py\n")
        f.write("# Do not edit this file directly. Instead, edit config.json and run audiosetup.py with --initialize option.\n\n")

        # Write default PulseAudio configuration
        # Load default modules
        f.write("\n# Load default PulseAudio modules\n")
        f.write("load-module module-udev-detect\n")
        f.write("load-module module-native-protocol-unix\n")

        # Write remapped sinks based on configuration
        f.write("\n# PulseAudio config for remapped sinks\n\n")
        
        for device in device_dict.values():
            f.write(device.get_pulseaudio_card_config())

        print(f"Created PulseAudio config: {PULSE_CONFIG}")
    # Reload PulseAudio configuration
    try:
        subprocess.run(['pulseaudio', '-k'], check=False)
        subprocess.run(['pulseaudio', '--start'], check=False)
    except subprocess.CalledProcessError as e:
        logging.error(f"Error occurred while reloading PulseAudio configuration: {e}")

def cleanup_pulse_config():
    """Remove the auto-generated PulseAudio configuration file."""
    if os.path.exists(PULSE_CONFIG):
        os.remove(PULSE_CONFIG)
        print(f"Removed PulseAudio config: {PULSE_CONFIG}")
    else:
        print(f"No PulseAudio config found at {PULSE_CONFIG}. Nothing to clean up.")



def kill_all_mpd_instances():
    """Kill all running MPD instances."""
    try:
        subprocess.run(['pkill', '-f', 'mpd'], check=True)
        print("Killed all running MPD instances.")
    except subprocess.CalledProcessError as e:
        print(f"Error killing MPD instances: {e}")

def cleanup_configs():
    """Remove all auto-generated MPD config files."""
    if not os.path.exists(MPD_CONFIG_DIR):
        print(f"No MPD config directory found at {MPD_CONFIG_DIR}. Nothing to clean up.")
        return
    for filename in os.listdir(MPD_CONFIG_DIR):
        if filename.startswith('mpd_') and filename.endswith('.conf'):
            os.remove(os.path.join(MPD_CONFIG_DIR, filename))
            print(f"Removed config file: {filename}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Setup multiple MPD instances')
    parser.add_argument('--install', action='store_true', help='Initialize MPD configuration')
    parser.add_argument('--cleanup', action='store_true', help='Remove all auto-generated config files')
    parser.add_argument('--audio-processor', choices=['pulseaudio', 'pipewire'], help='Override auto-detection of audio processor.')
    parser.add_argument('json', help='Path to JSON configuration file')    
    args = parser.parse_args()

    processor_status = detect_audio_processor()
    audio_processor = None
    if not args.audio_processor:
        if not processor_status['pipewire'] and not processor_status['pulseaudio']:
            logging.error("No active audio processor detected (neither PipeWire nor PulseAudio)")
            exit(1)

        detected_processor = 'pipewire' if processor_status['pipewire'] else 'pulseaudio'
        print(f"Detected active audio processor: {detected_processor}")
        audio_processor = detected_processor
    else:
        if args.audio_processor == 'pipewire' and not processor_status['pipewire']:
            logging.warning("User specified PipeWire as audio processor, but it is not active")
        elif args.audio_processor == 'pulseaudio' and not processor_status['pulseaudio']:
            logging.warning("User specified PulseAudio as audio processor, but it is not active")
        audio_processor = args.audio_processor


    if args.install:
        # Create config foles for respective audio processor
        acquire_lock()

        config = readconfig.read_and_parse_json(args.json)
        if not config:
            print("Failed to read configuration. Exiting.")
            parser.print_help()
            exit(1)

        device_dict: dict[str, AudioDevice] = {}
        for audio_device in config.get('outputmappers', {}).get('audio_devices', []):
            device_dict[audio_device.get('name')] = config2audiodevice(audio_device)
        
        #print(f"Parsed audio devices: {list(device_dict.keys())}")


        if audio_processor == 'pipewire':
            create_wireplumber_config(device_dict)
            create_pipewire_config(device_dict)
        else:
            create_pulse_config(device_dict)
        # Adding a short delay to ensure audio processor has restarted before starting MPD instances
        time.sleep(1)
        release_lock()
